import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

export default async function postBuild({
  distDir,
  DIST_PUBLIC,
}: {
  distDir: string;
  DIST_PUBLIC: string;
}) {
  const SERVE_JS = 'serve-cloudflare.js';

  // Generate a serve file that:
  // 1. Imports the serverEntry and utilities from server/index.js
  // 2. Builds a Cloudflare Worker object with all handlers properly wrapped
  // 3. Re-exports named exports like Durable Objects
  const serveCode = `
// This file is auto-generated by Waku's Cloudflare adapter
//
// It builds a Cloudflare Worker by:
// - Using INTERNAL_runFetch for the fetch handler (sets up env correctly)
// - Extracting custom handlers from your server-entry.tsx default export
// - Wrapping them with proper env setup using INTERNAL_setAllEnv
// - Re-exporting Durable Objects as named exports
//
// To add custom handlers, export them from your server-entry.tsx default export:
//
//   export default {
//     ...serverEntry,
//     fetch: patchFetchForDev(serverEntry.fetch),
//     scheduled: async (event, env, ctx) => {
//       // Your scheduled handler
//     },
//   };
//
// To add Durable Objects, export them as named exports from server-entry.tsx:
//
//   export class MyDurableObject {
//     constructor(state, env) { ... }
//     async fetch(request) { ... }
//   }
//
import { INTERNAL_runFetch, unstable_serverEntry } from './server/index.js';
import { INTERNAL_setAllEnv } from './server.js';

// Re-export named exports (Durable Objects, etc.)
export * from './server/index.js';

// Build the Cloudflare Worker object
// This extracts custom handlers from serverEntry and wraps them with env setup
const worker = {
  fetch: (request, env, ctx) => INTERNAL_runFetch(env, request, env, ctx),
};

// Conditionally add custom handlers if they exist on the serverEntry
if (typeof unstable_serverEntry?.scheduled === 'function') {
  worker.scheduled = async (event, env, ctx) => {
    INTERNAL_setAllEnv(env);
    return unstable_serverEntry.scheduled(event, env, ctx);
  };
}

if (typeof unstable_serverEntry?.queue === 'function') {
  worker.queue = async (batch, env, ctx) => {
    INTERNAL_setAllEnv(env);
    return unstable_serverEntry.queue(batch, env, ctx);
  };
}

if (typeof unstable_serverEntry?.tail === 'function') {
  worker.tail = async (events, env, ctx) => {
    INTERNAL_setAllEnv(env);
    return unstable_serverEntry.tail(events, env, ctx);
  };
}

if (typeof unstable_serverEntry?.trace === 'function') {
  worker.trace = async (traces, env, ctx) => {
    INTERNAL_setAllEnv(env);
    return unstable_serverEntry.trace(traces, env, ctx);
  };
}

export default worker;
`;
  const outDir = path.resolve(distDir);
  const assetsDistDir = path.join(outDir, 'assets');
  const workerDistDir = path.join(outDir, 'worker');

  fs.writeFileSync(path.join(outDir, SERVE_JS), serveCode);

  separatePublicAssetsFromFunctions({
    outDir,
    assetsDir: assetsDistDir,
    functionDir: workerDistDir,
  });

  const wranglerTomlFile = path.resolve('wrangler.toml');
  const wranglerJsonFile = path.resolve('wrangler.json');
  const wranglerJsoncFile = path.resolve('wrangler.jsonc');
  if (
    !fs.existsSync(wranglerTomlFile) &&
    !fs.existsSync(wranglerJsonFile) &&
    !fs.existsSync(wranglerJsoncFile)
  ) {
    fs.writeFileSync(
      wranglerJsoncFile,
      `\
{
  "name": "waku-project",
  "main": "./dist/worker/serve-cloudflare.js",
  // https://developers.cloudflare.com/workers/platform/compatibility-dates
  "compatibility_date": "2024-11-11",
  // nodejs_als is required for Waku server-side request context
  // It can be removed if only building static pages
  "compatibility_flags": ["nodejs_als"],
  // https://developers.cloudflare.com/workers/static-assets/binding/
  "assets": {
    "binding": "ASSETS",
    "directory": "./dist/assets",
    "html_handling": "drop-trailing-slash",
    "not_found_handling": "404-page"
  }
}
`,
    );
  }

  function copyFiles(
    srcDir: string,
    destDir: string,
    extensions: readonly string[],
  ) {
    const files = fs.readdirSync(srcDir, { withFileTypes: true });
    for (const file of files) {
      const srcPath = path.join(srcDir, file.name);
      const destPath = path.join(destDir, file.name);
      if (file.isDirectory()) {
        fs.mkdirSync(destPath, { recursive: true });
        copyFiles(srcPath, destPath, extensions);
      } else if (extensions.some((ext) => file.name.endsWith(ext))) {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }

  function copyDirectory(srcDir: string, destDir: string) {
    const files = fs.readdirSync(srcDir, { withFileTypes: true });
    for (const file of files) {
      const srcPath = path.join(srcDir, file.name);
      const destPath = path.join(destDir, file.name);
      if (file.isDirectory()) {
        fs.mkdirSync(destPath, { recursive: true });
        copyDirectory(srcPath, destPath);
      } else {
        fs.copyFileSync(srcPath, destPath);
      }
    }
  }

  function separatePublicAssetsFromFunctions({
    outDir,
    functionDir,
    assetsDir,
  }: {
    outDir: string;
    functionDir: string;
    assetsDir: string;
  }) {
    const tempDist = path.join(
      os.tmpdir(),
      `dist_${crypto.randomBytes(16).toString('hex')}`,
    );
    const tempPublicDir = path.join(tempDist, DIST_PUBLIC);
    const workerPublicDir = path.join(functionDir, DIST_PUBLIC);

    // Create a temp dir to prepare the separated files
    fs.rmSync(tempDist, { recursive: true, force: true });
    fs.mkdirSync(tempDist, { recursive: true });

    // Move the current dist dir to the temp dir
    // Folders are copied instead of moved to avoid issues on Windows
    copyDirectory(outDir, tempDist);
    fs.rmSync(outDir, { recursive: true, force: true });

    // Create empty directories at the desired deploy locations
    // for the function and the assets
    fs.mkdirSync(functionDir, { recursive: true });
    fs.mkdirSync(assetsDir, { recursive: true });

    // Move tempDist/public to assetsDir
    copyDirectory(tempPublicDir, assetsDir);
    fs.rmSync(tempPublicDir, { recursive: true, force: true });

    // Move tempDist to functionDir
    copyDirectory(tempDist, functionDir);
    fs.rmSync(tempDist, { recursive: true, force: true });

    // Traverse assetsDir and copy specific files to functionDir/public
    fs.mkdirSync(workerPublicDir, { recursive: true });
    copyFiles(assetsDir, workerPublicDir, [
      '.txt',
      '.html',
      '.json',
      '.js',
      '.css',
    ]);
  }
}
